### ISSUE TITLE
Includes not honoring file-relative paths

### ISSUE THREAD

**Issue by aaronla-ms** [mono/t4#106]
On the visual studio version of t4, relative include paths are resolved relative to the folder of the file making the reference. However, on mono/t4, the relative paths appear to be resolving relative to the current directory instead.

Repro

1. https://microsoft-my.sharepoint.com/:u:/p/aaronla_ntdev/EajxKzsUcQpPid8x-6oebHIBuOvAIA-IXka8cKILCaHIdg?e=1bvM1y (only visible to microsoft users)
    - folder\file.tt -- this file includes a reference to `<#@ include file="shared.ttinclude" #>`
    - folder\shared.ttinclude
2. dotnet tool restore
3. dotnet restore
4. dotnet build

[expected]
succeeds, produced folder\file.txt

[actual]
build fails, `error : Could not resolve include file 'shared.ttinclude'`

**Comment by aaronla-ms** [comment]
As noted in private thread, we can work around this issue for now by using the `-I` command line option.

**Comment by mhutch** [comment]
This was fixed in 4b175f5 in the `build-targets` branch.
