### ISSUE TITLE
[dotnet-t4] New error "The repository primary signature validity period has expired." when building iOS on AppCenter

### ISSUE THREAD

**Issue by anders9ustafsson** [mono/t4#115]
When trying to access *dotnet-t4* from an iOS project built on AppCenter (Xamarin iOS 14.14, XCode 12.4), the following error appears, and the `dotnet-t4` tool cannot execute.

> (TextTemplateTransform target) -> 
>   EXEC : warning NU3028: Package 'dotnet-t4 2.2.1' from source 'https://api.nuget.org/v3/index.json': The repository primary signature's timestamp found a chain building issue: ExplicitDistrust: The trust setting for this policy was set to Deny. 
> ...
> (TextTemplateTransform target) -> 
>   EXEC : error NU3037: Package 'dotnet-t4 2.2.1' from source 'https://api.nuget.org/v3/index.json': The repository primary signature validity period has expired.
> XXX.csproj(55,5): error MSB3073: The command "dotnet tool restore" exited with code 1.
 
I have been able to build the iOS AppCenter app with *dotnet-t4 2.2.1* included since February, with no problems, but only today it started failing permanently. The crash only occurs when building for iOS, for Android (Xamarin Android 11.1) the build still succeeds.

**Comment by anders9ustafsson** [comment]
As a temporary workaround I have switched to using the 2.3.0-preview from Github packages, but this requires separat access to Github packages and is not an acceptable permanent solution.

**Comment by mhutch** [comment]
The repository signature is added by the package repository, which in this case is NuGet.org. It looks like the NuGet client library used by `dotnet` is for some reason unable to validate the certificate used by NuGet.org. There's nothing I can do about this, unfortunately.

This is probably specific to Mac. I'm guessing your Android build takes place on a Windows host? The only NuGet issue I can find that mentions `ExplicitDistrust` is this *very* recently opened Mac-specific issue: https://github.com/NuGet/Home/issues/11178.

There are a few other similar looking issues such as https://github.com/NuGet/Home/issues/11099 but the `ExplicitDistrust` issue looks like the best match. It's a very specific error code, and it's happening on the same OS where you're seeing the problem (determining trust is often delegated to the OS).

**Comment by dtivel** [comment]
If this is on macOS, then https://github.com/NuGet/Home/issues/11178 is correct and updating dotnet should resolve it.  See https://github.com/dotnet/core/issues/6595#issuecomment-905086918.  I can't tell what version of dotnet is in use, but a more recent version of .NET 5 or .NET 6 should resolve it.

https://github.com/NuGet/Home/issues/11099 applies narrowly to a seemingly random "RPC busy" failure during any chain building involving a 3rd party root CA on Windows.  It does not apply to any other OS.
