### ISSUE TITLE
Add MSBuild targets package

### ISSUE THREAD

**Issue by mhutch** [mono/t4#12]
Create a package that contains MSBuild targets for transforming on build. It should work on both Mono and .NET Core.

**Comment by mhutch** [comment]
Not sure offhand what the best way to do this is. For precompiled templates I kinda like the idea of generating into the intermediate directory and injecting into the build, like xaml.

For normal templates I'd probably add wildcard items to automatically group the generated file under the parent. See Xamarin forms for an example of this.

In both cases I'd add metadata to wire up an MSBuild target as a generator so the files get updated on save.

**Comment by heaths** [comment]
I helped put the unofficial-but-still-Microsoft T4 package together for nuget.org. I was thinking of basically just copying that. I should have some time this weekend to work on it since I have an immediate need.

**Comment by mhutch** [comment]
Do you have a link?

**Comment by mhutch** [comment]
Oh, also, I wonder if it might make sense to create a project tool package first, and have the T4 engine invoke that tool? https://github.com/mono/t4/issues/10

**Comment by heaths** [comment]
Perhaps. I'm also talking with the .NET team about such a tool based on their newer templating engine they use for "dotnet new". Roslyn is also working on source generators. I'd rather avoid naming conflicts, so maybe tying this with either "mono" or "T4" (since the other stuff would not be T4-compatible directly).

Besides, since both .NET Framework and .NET Core are supported by this package, I'd really prefer supporting either with a binary task, or just write a target that invokes TextTransform.exe like the T4 build package does. That has no dependency on the dotnet CLI and could work for either. Regardless of any future changes for the dotnet CLI, I think supporting both vanilla MSBuild and the dotnet CLI would be best.

**Comment by mhutch** [comment]
Agree on runtime agnostic tasks, but you'll still need a texttransform.exe, and that will have dependencies too 🙂

**Comment by heaths** [comment]
True, and that should be .NET Core with runtime binaries; however, an MSBuild Core task should also work for MSBuild 15+, MSBuild Core / dotnet CLI. Also wouldn't have to marshal a lot of data across the command line. But I could see it either way.

**Comment by mhutch** [comment]
Yup that's a pretty good argument for using a task. That approach also simplifies csc invocation - you can just pass CscToolPath to the task. Whereas a netcore exe would have to depend on Roslyn.

**Comment by heaths** [comment]
csc invocation for this? I wasn't expecting / planning on anything like that - mainly just porting what I did for Microsoft's TextTransform.exe targets (though using a task, most likely).

**Comment by mhutch** [comment]
Textttransform uses codedom to compile the generated c# before loading and executing it. On netframework it uses the old csc 4.0 from the framework directory, on mono it uses a recent Roslyn csc from the framework directory. I have no idea what codedom on netcore does, but worst case we can grab the csc path from the msbuild environment and invoke it.

**Comment by thomaslevesque** [comment]
Any news on this? I'd be very interested in a MSBuild task that transforms templates on build!

**Comment by heaths** [comment]
Sorry, no. I started work on it but other projects took precedence.

**Comment by mhutch** [comment]
I have some WIP at https://github.com/mono/t4/tree/build-targets

It's functional but doesn't do incremental builds

**Comment by thomaslevesque** [comment]
Thanks @mhutch 

> It's functional but doesn't do incremental builds

What do you mean exactly? It will always re-run the template transformations?

**Comment by mhutch** [comment]
> What do you mean exactly? It will always re-run the template transformations?

Yes

**Comment by jazzdelightsme** [comment]
> [heaths] I helped put the unofficial-but-still-Microsoft T4 package together for nuget.org.
> [mhutch] Do you have a link?

It's here: https://www.nuget.org/packages/Unofficial.Microsoft.TextTemplating.BuildTasks/

Would LOVE to get a drop-in replacement for it.

**Comment by jjmanton** [comment]
@mhutch Just curious if you are still working on that branch for msbuild targets. We'd love a solution as well to replace https://www.nuget.org/packages/Unofficial.Microsoft.TextTemplating.BuildTasks/ that would work cross platform.

Thanks!

**Comment by mhutch** [comment]
Yes, it's still on my backlog but I can't promise when I'll have time to work on it, sorry

**Comment by bricelam** [comment]
Bonus points if it's compatible with the [existing MSBuild properties, items, and targets](https://docs.microsoft.com/visualstudio/modeling/code-generation-in-a-build-process)...

**Comment by mhutch** [comment]
there's some basic compat in there but I wanted to do better :)

**Comment by mhutch** [comment]
Just realized I never updated this issue when I opened the PR https://github.com/mono/t4/pull/110! Preview packages are available [in GitHub package registry](https://github.com/orgs/mono/packages?repo_name=t4) and the PR has a lot of details on the current status.

**Comment by TheConstructor** [comment]
@mhutch sounds great! Any estimate when this might hit nuget.org?
