### ISSUE TITLE
ProcessTemplate does not work in .NET 6 WinForms application.

### ISSUE THREAD

**Issue by Odraio** [mono/t4#122]
The `ProcessTemplate` seems to freeze (runs indefinitely) while executing the method in a .NET 6 **WinForms** application. If I execute the exact same code in a .NET 6 ConsoleApplication everything works. What is causing this unexpected behavior? A bug in my code sample or in the mono T4 library?

```
string inputFile = @"C:\Test\Test.tt";
string outputFile = @"C:\Output\TestClass.cs";
var generator = new TemplateGenerator();
generator.ProcessTemplate(inputFile, outputFile);
```

Test.tt file content:

```
<#@ template debug="false" hostspecific="true" language="C#" #>
<#@ output extension=".cs" #>
//----------------------------------------------------
//
// THIS IS AN AUTO GENERATED FILE.
//
//----------------------------------------------------

using System;

namespace MyApp
{
    public class Test
    {
            
    }
}
```

**Comment by mhutch** [comment]
My guess is it has something to do with the library's internal use of async/await interacting with the WinForms `SynchronizationContext`. I'll try to repro.

**Comment by Odraio** [comment]
@mhutch Will this fix be availble in a new NuGet package? It seems https://www.nuget.org/packages/Mono.TextTemplating is pretty far behind (in comparison to https://github.com/mono/t4/packages/38453)

**Comment by devlead** [comment]
It doesn't automatically to NuGet.org, but it does to GitHub packages so you can use that feed if you need quick access to binaries
https://github.com/mono/t4/packages/38453
