### ISSUE TITLE
dotnet-t4: Default extension is .txt when -c is specified

### ISSUE THREAD

**Issue by bricelam** [mono/t4#130]
When preprocessing a template...

```sh
t4 -c MyTemplate MyTemplate.tt
```

...it uses the `.txt` extension. This forces me to also specify the `-o` option. (Leading to lots of redundancy.)

```sh
t4 -o MyTemplate.cs -c MyTemplate MyTemplate.tt
```

As stated in #128, Visual Studio will peak at the `template` directive and use `.cs` for C# and `.vb` for VB.

**Comment by mhutch** [comment]
Yes, definitely makes sense to default to a code extension when generating a class :)
