### ISSUE TITLE
Any plans on publishing updates on nuget.org?

### ISSUE THREAD

**Issue by anders9ustafsson** [mono/t4#133]
We are currently forced to use one of the 2.3.0 pre-releases of _dotnet-t4_ in our apps, which means that we need to fetch the package from Github. This means we need to store Github credentials in our _nuget.config_ file to be able to download the package. It would be considerably more convenient for us being able to download from _nuget.org_ instead. Could we hope for updates being published to _nuget.org_ in the near future?

**Comment by AraHaan** [comment]
I think a better place would be for them to consider storing the packages on azure like how the .NET Foundation does it.

**Comment by mhutch** [comment]
Final 2.3.0 builds are now live on NuGet.org. Apologies for the delay!

**Comment by AraHaan** [comment]
Could you guys consider setting it up to where every commit (non-tag releases) gets published to nuget.org or to azure packages as well?
