### ISSUE TITLE
Question: Can you generate/expose an intermediate .cs file for SAST?

### ISSUE THREAD

**Issue by irishismyname** [mono/t4#135]
I'm trying to automate SAST of T4 templates and I was wondering if Mono/t4 is capable of generating some kind of intermediate .cs file.

## Given `template.tt`
```csharp
<#@ template language="C#" #>
<#@ assembly name="System.Core" #>
<#@ import namespace="System.Text" #>
<#@ output extension=".txt" #>
Static Text!
<#
    for (int i=0; i<10; i++) {
    WriteLine("Hello!");
    }
#>
```

## Produce (something like)
```csharp
using System.Core;
using System.Text;

public class T4TemplateSource
{
    private readonly System.Text.StringBuilder builder = new System.Text.StringBuilder();

    public static void Main(string[] args)
    {
        var template = new T4TemplateSource();
        var text = template.Execute(args);
        System.IO.File.WriteAllText(System.IO.Path.ChangeExtension(filename, ".txt"), text);
    }

    private string Execute(string[] args)
    {
        builder.Append(@"Static Text!");
        for (int i=0; i<10; i++)
        {
            builder.Append(@"Hello!\n");
        }
    }
}
```

**Comment by irishismyname** [comment]
Running `t4 template.tt --verbose` pointed me to `C:\Users\username\AppData\Local\Temp\tmpXXXX.tmp\response.rsp`, which in turn pointed me to `C:\Users\username\AppData\Local\Temp\tmpYYYY.tmp\GeneratedTextTransformation.cs` which was the file I was looking for. Still curious if there's a more direct way to obtain this file.

**Comment by mhutch** [comment]
It sounds like what you want is runtime templates (aka "preprocessed templates"). Pass a class name to `t4` using `-c SomeClassName` and it will output the template class, which you can then compile and execute any way you want.
