### ISSUE TITLE
Is `dotnet-t4-project-tool` deprecated?

### ISSUE THREAD

**Issue by Youssef1313** [mono/t4#136]
The README in the repo root mentions this package as deprecated. However:

1. https://github.com/mono/t4/packages/38452 mentions: "To install in a project as a DotNetCliToolReference, use dotnet-t4-project-tool instead."
2. It looks like `dotnet-t4-project-tool` is still receiving updates.

**Comment by mhutch** [comment]
Yes, it is, as .NET project tools in general are deprecated in favor of [local tools](https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-local-tool). I'll update the descriptions.

**Comment by mhutch** [comment]
The `dotnet-t4-project-tool` package is now deprecated on nuget.org and in the readme.md of version 2.3.x.
