### ISSUE TITLE
MsBuild package release ?

### ISSUE THREAD

**Issue by Rivsoft** [mono/t4#153]
Hi @mhutch:

I was wondering what the roadmap would look like for releasing the MSBuild targets. I am currently upgrading a pretty large application from net 472 to .net 6 and one aspect that doesnt work is the t4 generation for both target frameworks. 

Using the CLI tool works but its cumbersome due to an additional dependency having to be installed and a dotnet restore on the cli tool having to be run on build agents for it to work so I would prefer to run a msbuild targets as it is done with current VS TextTemplating msbuild targets today.

I noticed another project trying to solve this issue with running templates under .net core (https://github.com/jgiannuzzi/T4.Build) and even noticed you were interested in merging those changes so I will rather look for a more "official" solution to this problem rather than using old packages etc.

I was able to get latest code and build the msbuild package myself but I noticed a few issues so was wondering what would be Mono's roadmap about this getting officially released.

I can help with testing the packages etc but to be honest I am not an expert on how to debug the engine etc my self.

Thanks and really appreciate the Mono team work.

**Comment by mhutch** [comment]
Sorry about this! Had it almost ready to go, ran into some CI issues, then got distracted by other things. I will take a look at getting it out soonish.

**Comment by gaurav137** [comment]
Any update on this issue? I'm also invoking dotnet T4 manually to generate files but having it integrated as part of the build will be ideal

**Comment by TheConstructor** [comment]
I was able to use Mono.TextTemplating.Build version 2.3.0-preview-0048-g38de54eb32 successfully through github repositories, but I would love to have it in nuget.org, so I don't need to wonder which github credentials are correct on a build server. I don't feel like my personal access token belongs there...

It would be great, if you found time to get this out :D

**Comment by mhutch** [comment]
I have pushed a prerelease version of the package to NuGet.org :)

**Comment by TheConstructor** [comment]
Thank you for publishing https://www.nuget.org/packages/T4.BuildTools/3.0.0-preview-0027-g2711105671 !

**Comment by mhutch** [comment]
Closing for now, please report any problems you run into using the package and hopefully I can make a stable release soon!
