### ISSUE TITLE
Is this project the future of T4

### ISSUE THREAD

**Issue by redoz** [mono/t4#19]
I spent some time trying to figure out if Microsoft had open-sourced the T4 engine or not when I found this. As mono is now part of Microsoft, will this be the "vNext" of T4, or will both projects move forward in parallel?

**Comment by ericsink** [comment]
I can't answer your question or speak for the maintainer(s), but I can say this:  My team uses this library a lot, and I'm really glad to see recent work toward making it compatible with .NET Core.  :-)

**Comment by mhutch** [comment]
I can't speak for the team that developed/maintains the original T4 implementation, but I plan to continue developing and maintaining this one.
