### ISSUE TITLE
Changelog For v3.0.0

### ISSUE THREAD

**Issue by mark-monteiro** [mono/t4#194]
There doesn't appear to be any changelog or release notes for the new version 3.0.0. Would it be possible to add a changelog to this project so we can know what was changed before attempting to upgrade?

**Comment by Pxtl** [comment]
Yes, when I went to upgrade a project's dependencies I saw 3.0.0 was out and came here to look for documentation on what the implications are and found nothing.  Major version bump generally means breaking backwards compatibility so information would be really appreciated.

**Comment by mark-monteiro** [comment]
@mhutch Looking at the [comparison](https://github.com/mono/t4/compare/v2.3.1...v3.0.0) between v3.0.0 and the previous release v.2.3.1, all of the changes are yours. Would you be able to provide a brief summary of the changes or at least any major breaking changes? That would be very helpful for anyone looking to upgrade.

**Comment by mhutch** [comment]
The major change in Mono.TextTemplating 3.0.0 is the addition of a new `T4.BuildTools` package. This contains MSBuild targets for build-time text transformations. Although fully featured, it has not been extensively tested and further feedback would be appreciated. These targets are documented in the package [README.md](https://github.com/mono/t4/blob/main/Mono.TextTemplating.Build/readme.md) and include a bundled schema for the [MSBuild Editor](https://github.com/mhutch/MonoDevelop.MSBuildEditor). These targets are fully integrated into the Visual Studio design time build and mechanisms for executing targets on save, making it straightforward to migrate to  Mono.TextTransform from the VS T4 engine.

Although there are no API breaking changes, the major version was bumped following SemVer rules as there are multiple changes to assembly loading rules that could result in breaking behavioral changes in some cases.

* Fixed [assembly resolution bugs](https://github.com/mono/t4/commit/2aea69215c681691281f4e7114f07c65fe4d6327) specific to the `AssemblyLoadContext` codepath used on .NET Core. It should now be consistent with the assembly resolution behavior with `AppDomain` on .NET Framework.
* Added a [`DisableAssemblyLoadContext` host option](https://github.com/mono/t4/commit/79ec659a452ac87aaf1d2ac28b27da8065ab3d25) to opt out of `AssemblyLoadContext` usage.
* Assemblies known to the host now [take precedence](https://github.com/mono/t4/commit/ad28c474dd7d955b477c64ccd2ad14c98b0da531) over identically-named assemblies passed to the generator. This prevents issues where a reference assembly passed to the host would fail to load at runtime.
* When the host specifies to use the current AppDomain for template execution, then the AppDomain codepaths will be skipped entirely. This optimization may lead to changes in assembly loading behavior.

There are also miscellaneous bug fixes and improvements to compatibility with newer .NET and C# version:

* Handling of the C# language version has been reworked ([1](https://github.com/mono/t4/commit/51a5db5415dc2387e28e81f27da1086e7035bcb8), [2](https://github.com/mono/t4/commit/56f20c81e90f837a494d775388a48de55045a491)). The language version and runtime version are now decoupled, and when a language version is not explicitly specified, it will default to the highest language version supported by the target runtime.
* .NET 9 and C# 12 are now supported.
* The CLI tool now has a [`--useRelativeLinePragmas`](https://github.com/mono/t4/pull/154) argument.
* The `DOTNET_ROOT` environment variable is now respected.
* The new `CreateTempSubdirectory` method from .NET 7 is now used for temp directory creation, massively reducing the chance of temp directory name collisions. This has also been [backported to older runtimes](https://github.com/mono/t4/commit/86c58e1955b94d5492bea37f1584c81ff74f42dc)

**Comment by mark-monteiro** [comment]
Thank you so much for the detailed response! The T4.BuildTools package looks super useful I will give a try when I have time
