### ISSUE TITLE
Support for referencing netstandard1.6/2.0 assemblies

### ISSUE THREAD

**Issue by mhutch** [mono/t4#21]
In order to support referencing netstandard1.6/2.0 assemblies, the host needs to inject the corresponding facades

**Comment by Phrohdoh** [comment]
What is the state of referencing `netstandard2.0` assemblies in `tt` documents with this T4 implementation?

**Comment by mhutch** [comment]
It depends. If the engine runs on .NET Core then referencing netstandard2.0 assemblies won't be an issue as netstandard.dll will be referenced automatically. If the engine is running on .NET Framework or Mono, then it won't work.

**Comment by Phrohdoh** [comment]
I'm having an issue loading a `netstandard2.0` library in a T4 document in a `netcoreapp2.2` project. Should I open a separate ticket for this?

**Comment by mhutch** [comment]
Now I think about it, I'm not sure we reference netstandard.dll by default.

I think the simplest way to handle this would be to inspect the references of referenced assemblies, and attempt to resolve those. That means we'd either have to load them using reflection (not good) or add a dependency for reading assembly metadata such as Mono.Cecil.

**Comment by mhutch** [comment]
This is fixed in 2.2.0, all the reference assemblies that a csproj would reference are now referenced.
