### ISSUE TITLE
Support net core

### ISSUE THREAD

**Issue by ErliSoares** [mono/t4#23]
I made some changes to work with the net core, I did some tests with version 2.1 and it worked for my context, I would like to use the official library with support for the net core, below the link of the repository with the changes, maybe it helps in something.

https://github.com/ErliSoares/t4

The biggest change was the compilation of the template, which I had to use roslyn which has support for all platforms, windows, linux...

**Comment by atifaziz** [comment]
@ErliSoares Have you looked at [T5](https://github.com/atifaziz/t5)? I did something similar back in February. See [my comment](https://github.com/mono/t4/issues/8#issuecomment-363590843) to issue #8 for some background and discussion.

**Comment by ErliSoares** [comment]
I had looked at the T5, I even took some ideas from there, but I had trouble putting it to work in my scenario.
What I really missed is seeing the file with the source code of the generated template, to make it easier to identify errors with complex templates.
Maybe I'm even mistaken, I do not know how roslyn works, but how did the compilation in memory is difficult to debug.
https://github.com/atifaziz/t5/blob/master/src/TextTemplating/TemplatingEngine.cs#L210

I did this in order to get debug:
https://github.com/ErliSoares/t4/blob/master/Mono.TextTemplating/Mono.TextTemplating/TemplatingEngine.cs#L270

Thank you very much

**Comment by atifaziz** [comment]
> What I really missed is seeing the file with the source code of the generated template

Run `dotnet tt --help` and see the `-c` option:

```
TextTransform command line T4 processor
Usage: dotnet-tt [options] input-file
Options:
  -o, --out=file             The name of the output file
  -r=VALUE                   Assemblies to reference
  -u=namespace               Namespaces to import <namespace>
  -I=VALUE                   Paths to search for included files
  -P=VALUE                   Paths to search for referenced assemblies
      --dp=VALUE             Directive processor (name!class!assembly)
  -a=VALUE                   Parameters (name=value) or 
                               ([processorName!][directiveName!]name!value)
  -h, -?, --help             Show help
  -c=class                   Preprocess the template into class
```

So now running something like `dotnet tt -c=Foo.Bar FooBar.tt` will create a file with the generated template source code that you can either use for debugging or embedding into a library for reuse at run-time.

**Comment by mhutch** [comment]
This is now fixed :)
