### ISSUE TITLE
Publish as a per-project tool (DotNetCliToolReference)

### ISSUE THREAD

**Issue by atifaziz** [mono/t4#28]
Publish as a [per-project tool](https://docs.microsoft.com/en-us/dotnet/core/tools/extensibility#per-project-based-extensibility) so projects can reference and restore t4 via `DotNetCliToolReference`.

This is needed until a project can be upgraded to .NET Core 3.0 (when it's out) and can switch over to [local tools](https://github.com/dotnet/cli/issues/10288) (dotnet/cli#10288).

**Comment by mhutch** [comment]
Agreed, this makes sense! I'm kinda surprised global tools can't be installed project-local though.

**Comment by atifaziz** [comment]
> 'm kinda surprised global tools can't be installed project-local though.

It is surprising and per my research into this earlier, you have to package the two (global and per-project) separately. See:

https://github.com/atifaziz/t5/issues/3#issuecomment-397344229

**Comment by atifaziz** [comment]
Yay! 👍 

Seems [un-published](https://www.nuget.org/packages/dotnet-t4-project-tool/) at the moment though, but coming soon?

**Comment by mhutch** [comment]
Yup, just need to test the package

**Comment by mhutch** [comment]
It's live, `dotnet-t4-project-tool`

**Comment by atifaziz** [comment]
@mhutch Working like a charm so far! Thank you ever so much!

**Comment by Konard** [comment]
https://github.com/Konard/T4GenericsExample here it is working too.
