### ISSUE TITLE
Question: Is there any document about how to use dotnet-t4 global tool?

### ISSUE THREAD

**Issue by WeihanLi** [mono/t4#39]
Question: Is there any document about how to use the `dotnet-t4` global tool?

For example:

- How to generate file from the template
- Can I use it for code generation without Visual Studio

**Comment by devlead** [comment]
Disclaimer not a maintainer, but there's a short example in the [README.md](https://github.com/mono/t4/blob/master/README.md#monotexttemplating)


```bash
dotnet tool install -g dotnet-t4
echo "<#@ parameter name='Name' #>Hello <#=Name#>" | t4 -o - -p:Name=World
Hello World
``` 

>   How to generate file from the template

```bash
t4 Test.tt
```
specify output filename

```bash
t4 Test.tt -o Test.cs
```

>  Can I use it for code generation without Visual Studio

Yes, that's the purpose of the tool.

**Comment by WeihanLi** [comment]
Thank you so much @devlead
