### ISSUE TITLE
Cannot resolve .NET Core 3.0 assemblies

### ISSUE THREAD

**Issue by stevenbrix** [mono/t4#47]
**Repro**

1. Save the following to `TextTemplate1.tt`

```
<#@ template debug="false" hostspecific="false" language="C#" #>
<#@ assembly name="System.Core" #>
<#@ assembly name="System.Text.Json" #>
<#@ import namespace="System.Linq" #>
<#@ import namespace="System.Text" #>
<#@ import namespace="System.Collections.Generic" #>
<#@ output extension=".cs" #>

public class TextTemplateClass
{
}
```

2. Run `t4 TextTemplate1.tt`

**Expected**
`System.Text.Json` assembly is discoverable via the shared runtime installation on the machine

**Actual**
Processing '.\TextTemplate1.tt' failed.
ERROR: Metadata file 'System.Text.Json.dll' could not be found

**Comment by stevenbrix** [comment]
Note that changing this line:
`<#@ assembly name="System.Text.Json" #>`
to:
`<#@ import namespace="System.Text.Json" #>`

produces this error:
C:\Users\skirb\AppData\Local\Temp\tmpF3E7.tmp\GeneratedTextTransformation2435a7b7.cs(14,23): ERROR: The type or namespace name 'Json' does not exist in the namespace 'System.Text' (are you missing an assembly reference?)

**Comment by mhutch** [comment]
Pretty sure this would involve either running on .NET Core 3.0 or implementing NuGet support

**Comment by mhutch** [comment]
See https://github.com/mono/t4/issues/15

**Comment by mhutch** [comment]
I think this specific assembly resolution issue will be fixed when I update this to run on .NET Core 3.0 after it's released.

**Comment by graphdb2** [comment]
Hello, any plan to release with .net core 3.0 ? thanks, it also solve the issue on loading net standard library.

**Comment by anomaly2** [comment]
This is still an issue. Is fixing this anywhere on the roadmap?

**Comment by kccarter76** [comment]
hmm, this sounds like something that I have been working on, in pursuit of implementing a specialized T4 templating integration with visual studio using this engine. I have discovered for the most part that the assemblies used by the .net core runtime compiler really do not like to be loaded in .net framework. you can track the branch I am working out of here. 

[SubSonic Core T4 Fork](https://github.com/SubSonic-Core/t4)

**Comment by jogibear9988** [comment]
I've also fixed some of the loading problems in my pull req against @kccarter76  s fork

**Comment by mhutch** [comment]
I just pushed a fix for this. It now references all the assemblies that are automatically referenced from a modern csproj.

```bash
$ echo "<#=new System.Text.Json.JsonSerializerOptions().ReadCommentHandling#>" | t4 -o -
Processing failed.
(1,121): ERROR: The type or namespace name 'Json' does not exist in the namespace 'System.Text' (are you missing an assembly reference?)

$ echo "<#=new System.Text.Json.JsonSerializerOptions().ReadCommentHandling#>" | dotnet bin/Debug/net5.0/t4.dll -o -
Disallow
```

**Comment by autosend-ug** [comment]
> 
> 
> Note that changing this line: `<#@ assembly name="System.Text.Json" #>` to: `<#@ import namespace="System.Text.Json" #>`
> 
> produces this error: [..]

You need **both** lines:

```
<#@ assembly name="System.Text.Json" #>
<#@ import namespace="System.Text.Json" #>
```

And this works fine.
