### ISSUE TITLE
System.Runtime.Remoting not supported in .net Standard 2.0

### ISSUE THREAD

**Issue by reflectedobject** [mono/t4#49]
Cannot invoke template in .net Standard library due to generated to containing: "System.Runtime.Remoting".
The generated template (*.cs) does not compile due to the Remoting reference.

Any suggestions?

TT: TextTemplatingFilePreprocessor
Assembly: .net Standard Library 2.0

**Comment by mhutch** [comment]
Which version is this with? How are you invoking it?

**Comment by maulwuff** [comment]
I don't think it is related to mono.
This happens for me, when there is a parameter involved on a pure windows environment:

parent tt file has an include statement:
```
<#@ include file="..\some.ttinclude" #>
```

the included file defines a paramter:
```
<#@ parameter type="System.String" name="sourceFile" #>
```

which results in:

```
public override void Initialize()
{
	base.Initialize();
	if ((this.Errors.HasErrors == false))
	{
		bool sourceFileValueAcquired = false;
		if (this.Session.ContainsKey("sourceFile"))
		{
			this._sourceFileField = ((string)(this.Session["sourceFile"]));
			sourceFileValueAcquired = true;
		}
		if ((sourceFileValueAcquired == false))
		{
			object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("sourceFile");
			if ((data != null))
			{
				this._sourceFileField = ((string)(data));
			}
		}
	}
}
```

**Comment by mhutch** [comment]
That's very odd. The call to `LogicalGetData` is only emitted when `FEATURE_APPDOMAINS` is true: https://github.com/mono/t4/blob/ce07629659b515b95e310f70fab2bb27c29c48b5/Mono.TextTemplating/Microsoft.VisualStudio.TextTemplating/ParameterDirectiveProcessor.cs#L220

And `FEATURE_APPDOMAINS` is only true for the `net40` and `net35` builds of the library: https://github.com/mono/t4/blob/cc6dd782a6d828a3a4809de84376b53f95a66c31/Mono.TextTemplating/Mono.TextTemplating.csproj#L11

Can you give me a more complete repro case?

**Comment by maulwuff** [comment]
As I mentioned, this may not be a mono issue. I reproduced this in a pure Visual Studio 2019 environment using a .netStandard2.0 class library.

Microsoft Visual Studio Professional 2019
VisualStudio.16.Release/16.1.6+29102.190
Microsoft .NET Framework Version 4.7.03190

When you click "run custom tool" on the tt file you will find these two unsupported types:
- `global::System.CodeDom.Compiler.CompilerErrorCollection`
- `global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("sourceFile");`

The first one can be added via the System.CodeDom nuget package.

[ttSample.zip](https://github.com/mono/t4/files/3471087/ttSample.zip)

**Comment by mhutch** [comment]
Yes, that's using the T4 implementation in VS, not Mono.TextTemplating.
