### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by graphdb2** [mono/t4#55]
Hello,

I am getting this issue running this command : 
`t4 -r=C:\WorkingArea\rdxnoninstrument3\rdxnoninstrument\source\nwm.dx.rdxnoninstrument.message\bin\Debug\netcoreapp2.1\nwm.dx.rdxnoninstrument.message.dll Schema\Types\GraphTypes.t4`

T4 text template processor version 2.0.4+gaf154e27e2

This file exist : 
C:\WorkingArea\rdxnoninstrument3\rdxnoninstrument\source\nwm.dx.rdxnoninstrument.message\bin\Debug\netcoreapp2.1\nwm.dx.rdxnoninstrument.message.dll 

**ERROR: Error running transform: System.Reflection.TargetInvocationException: Exc
eption has been thrown by the target of an invocation. ---> System.IO.FileNotFou
ndException: Could not load file or assembly 'nwm.dx.rdxnoninstrument.message, V
ersion=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find th
e file specified. ---> System.IO.FileNotFoundException: Could not load the speci
fied file.
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName a
ssemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPt
r gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.TextTemplating.GeneratedTextTransformation6da4a4bd.
TransformText()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,
 Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke
Attr, Binder binder, Object[] parameters, CultureInfo culture)
   at Mono.TextTemplating.CompiledTemplate.Process() in /Users/mikayla/code/t4/M
ono.TextTemplating/Mono.TextTemplating/CompiledTemplate.cs:line 119**

otherwise you get a different message with a random file

ERROR: Metadata file 'C:\WorkingArea\rdxnoninstrument3\rdxnoninstrument\source\n
wm.dx.rdxnoninstrument.message\bin\Debug\netcoreapp2.1\dummy.dll' could not be found

**Comment by graphdb2** [comment]
I have added a project that reproduce this issue on dotnet core 2.1 

https://github.com/graphdb2/T4Test

**Comment by graphdb2** [comment]
This fix my issue but I do not know if it the correct solution  :

https://github.com/graphdb2/t4/commit/dc0d98001a53e307419384987a92e547074f7cc2

**Comment by mhutch** [comment]
I think that fix is correct, actually :) Could you please make a PR?

**Comment by 6opuc** [comment]
Can you please update nuget package with this fix?
