### ISSUE TITLE
Is there any support for transforming T4 files on every build?

### ISSUE THREAD

**Issue by alexrp** [mono/t4#57]
In one of my projects, I'd like to avoid committing the generated C# code to the repository. So I'm wondering if there is any kind of support for something like the `TransformOnBuild` property as described in [this SO answer](https://stackoverflow.com/a/3381556)? That specific solution isn't great since it requires having both VS and the VS SDK installed. That same SO topic also has a mention of [this project](https://github.com/clariuslabs/TransformOnBuild) but that would require knowing exactly where the project tool gets installed. (It also doesn't look like that project supports .NET Core.)

What I'm looking for would ideally be the ability to just add something like the following to my project file:

```xml
  <DotNetCliToolReference Include="dotnet-t4-project-tool" Version="2.0.5" />
  <ItemGroup>
    <None Include="SomeTemplate.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <TransformOnBuild>true</TransformOnBuild>
    </None>
    <Compile Include="SomeTemplate.cs">
      <DependentUpon>SomeTemplate.tt</DependentUpon>
    </Compile>
  </ItemGroup>
```

**Comment by mhutch** [comment]
Not currently. I've had some WIP sitting around on my disk for a while.

**Comment by mhutch** [comment]
https://github.com/mono/t4/tree/build-targets

**Comment by Prinsn** [comment]
Should the above link to something?  It's identical to https://github.com/mono/t4 for me.

**Comment by devlead** [comment]
@Prinsn there's several differences 
https://github.com/mono/t4/compare/build-targets

**Comment by Prinsn** [comment]
Oh, derp.  That's a brain fart.

**Comment by Konard** [comment]
Right now it is possible using [dotnet-t4-project-too](https://www.nuget.org/packages/dotnet-t4-project-tool), example at [Konard/T4GenericsExample](https://github.com/Konard/T4GenericsExample)

**Comment by mhutch** [comment]
Closing in favor of #12
