### ISSUE TITLE
Debug steps for project-tool install?

### ISSUE THREAD

**Issue by Prinsn** [mono/t4#59]
Previously was getting hung up on confusing errors but I managed to get it to theoretically install without error, but it doesn't appear to be recognized as a dotnet command as t4, t4-project or t4-project-tool.

Semi new to manual install vs nuget but installed as 
`dotnet add package dotnet-t4-project-tool --version 2.0.5`
In my proj directory, but 

```
PS ~> dotnet t4
No executable found matching command "dotnet-t4"
PS ~> dotnet t4-tool
No executable found matching command "dotnet-t4-tool"
PS ~> dotnet t4-project-tool
No executable found matching command "dotnet-t4-project-tool"
```

I feel like I'm just failing on the syntax for use, because dotnet says it exists

```
Project 'proj' has the following package references
   [netcoreapp2.2]:
   Top-level Package                                          Requested   Resolved
   > AspNet.Security.OpenIdConnect.Server                     2.0.0       2.0.0
   > dotnet-t4-project-tool                                   2.0.5       2.0.5
```

Trying to install it via nuget gives 
`'dotnet-t4-project-tool 2.0.5' has a package type 'DotNetCliTool' that is not supported by project`

**Comment by mhutch** [comment]
Not sure offhand what the CLI command is, but you can add it manually to your project file. Just add this in an `<ItemGroup>`:

`<DotNetCliToolReference Include="dotnet-t4-project-tool" Version="2.0.5" />`

Then you can do:

`dotnet tt`

Note the package is `t4` and the command is `tt` - kinda confusing, but the `dotnet-tt` package name was already taken.

**Comment by Prinsn** [comment]
I don't know if you know about the t5 project but I got that to work, but it's hit limitations and we'd rather use this up to date project, so I'm struggling as to why it doesn't work between the two.

I've added it to the project as another attempt, was just about to update with that.

Same kind of "404" non constructive error
`No executable found matching command "dotnet-tt"`

I shouldn't have to do anything other than build to have it added to the project, and then make sure I'm in the project directory when invoking the command, right?

**Comment by Prinsn** [comment]
Flummoxed.

`dotnet restore` and normal build execution aren't outputting any errors, just that the "no executable matching command"

Should there be a file generated anywhere that I could verify the existence of?

**Comment by Prinsn** [comment]
Also, speaking of the T5 project...

T5 also uses `dotnet tt` as its command.  Throwing it back in and it works immediately, even with both specified 

```
  <ItemGroup>
    <DotNetCliToolReference Include="dotnet-t4-project-tool" Version="2.0.5" />
  </ItemGroup>
  
  <ItemGroup>
    <DotNetCliToolReference Include="T5.TextTransform.Tool" Version="1.1.0-*" />
  </ItemGroup>
```

Is it possible to have a duplicate script conflict and it expect T5 despite having removed it?

**Comment by mhutch** [comment]
I honestly have no idea, sorry :/

**Comment by mhutch** [comment]
Oh, apparently I called the project tool `t4`, not `tt`. Oops.

**Comment by mhutch** [comment]
And the global tool. Guess I misremembered.

**Comment by Prinsn** [comment]
the -g path you suggest in the Readme?

I think I need to poke the server admin bears about that, getting a not found because I think it's hitting our proxy, which gives an explicit error.

Don't feel too :/ aboot it, this is non-critical code so there's no real work stoppage, just trying to convert from code that runs during server startup to a build step so that we can capture some metadata from some services and remove the generated code from version control.

Really appreciate the sanity check 😜

**Comment by Prinsn** [comment]
hahahahah...

As is the way of things, it suddenly started working.

```
PM> dotnet t4
T4 text template processor version 2.0.5+gb7c3b777e4
Usage: dotnet-t4 [options] input-file
Use --help to display options.
dotnet : No input file specified.
```

Wish I could put some better feedback for anyone that ends up here with similar problems but
`while(😫) {clean; rebuild; dotnet build;}` and maybe it'll work eventually.

**Comment by mhutch** [comment]
Does it fix the issue you saw in https://github.com/atifaziz/t5/issues/15?

**Comment by Prinsn** [comment]
Haven't gotten to that point yet.

Been doing some real blackmagicky things to work around it, have reverted to trying to reflect load the required assembly data instead of relying on the tool.

I've honestly never setup a t4 from scratch, so I'm not sure which what of the arguments they expect.

I'll probably be back if I can't get it to work and need to lean on the options.
