### ISSUE TITLE
Compilation hang-up

### ISSUE THREAD

**Issue by robertstefan** [mono/t4#63]
It's great having this project available, as I'm more comfortable for generating templates that output to html files.

But, for the last day or so, I've been stuck to a point where nothing was happening with the parser; it did not matter if I was using the latest nuget package, or the [latest source](https://github.com/mono/t4/commit/0eb8bf842f158e8b31fc7103c5c7c2a7603773ad).

After a step-by-step debug session, I've reached this [loc](https://github.com/mono/t4/blob/master/Mono.TextTemplating/Mono.TextTemplating.CodeCompilation/CscCodeCompiler.cs#L183) where the execution halted without any error.

I'm using the library inside a web project, maybe it has something to do with this? I'm not sure, but [here](https://gist.github.com/robertstefan/7b36876516905c5877acf7b4adbed6f8) is a snippet of the code from the project as I make use of it (maybe i'm doing something wrong)

**Comment by mhutch** [comment]
Can you pause it at the place it hung and get a stack trace?

**Comment by mhutch** [comment]
Please reopen if you see this again and can get a stack track.
