### ISSUE TITLE
Not compatible with dotnet core 3.0.0 

### ISSUE THREAD

**Issue by extmchristensen** [mono/t4#70]
I tried dotnet-t4 on mac with dotnet 3.0.0 installed  and while it could be installed, it failed to run (see below for details).

`dotnet tool install -g dotnet-t4`
You can invoke the tool using the following command: t4
Tool 'dotnet-t4' (version '2.0.5') was successfully installed.

`echo "<#@ parameter name='Name' #>Hello <#=Name#>" | t4 -o - -p:Name=World`
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.0.0 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

**Comment by devlead** [comment]
The latest code in this repo targets `netcoreapp3.0`, it's not released yet though.

What you can do for now is to set environment variable `DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX` to `2`.

Setting it to `2` will enable rolling forward major version automatically and executing under .NET Core `3` even though it's compiled for `2.1`

You can read more about this runtime feature at
https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-2-1#roll-forward

**Comment by extmchristensen** [comment]
@devlead Thanks for the tip. I look forward to the 3.0 release (could not get the DOTNET_ROLL_FORWARD_ON_NO_CANDIDATE_FX trick to work on mac unfurtunately).

**Comment by mhutch** [comment]
FWIW, you can get preview packages from https://github.com/mono/t4/packages

**Comment by anders9ustafsson** [comment]
@mhutch @devlead By any chance, are the preview packages available on any public NuGet server?

**Comment by devlead** [comment]
Yes,  the link @mhutch gave above is a nuget server, GitHub provides org nuget feeds now.
If you go to a package  i.e. below there's instructions on how to restore from it,  you can also download nupkg manually

https://github.com/mono/t4/packages/81821

**Comment by anders9ustafsson** [comment]
Many thanks, @devlead . More specifically, I am attempting this:

**Comment by anders9ustafsson** [comment]
After further investigation, I manged to get it to run locally, by also adding package source credentials to my nuget.config file. The initial problem with .NET Core appears to remain, though; when I build my code in a Bitbucket Pipeline or AppCenter with only .NET Core 3.1 installed, I get the same build error that the t4 tool is not compatible with .NET Core 3.x.

**Comment by anders9ustafsson** [comment]
Ok, I have now been able to find the reason why I still cannot run the *dotnet-t4-project-tool*; this tool is still at *netcoreapp2.0*, see [here](https://github.com/mono/t4/blob/master/dotnet-t4-project-tool/dotnet-t4-project-tool.csproj#L4). @mhutch @devlead Would it be possible for you to also bump up *dotnet-t4-project-tool* to .NET Core 3.0 and publish a new preview package?

**Comment by anders9ustafsson** [comment]
Ok, I managed to find out myself that *dotnet-t4-project-tool* cannot be built for .NET Core 3, it is only allowed for .NET Core 2.2. and lower. So the solution appears to be, to install *dotnet-t4* preview as a local tool and use that instead in my .csproj file. I have not entirely succeeded yet; my Bitbucket piepline and AppCenter builds are still giving me a hard time :-) But I hope to be able to fix the entire chain eventually. Thanks for providing this tool in the first place, it is much appreciated!

**Comment by anders9ustafsson** [comment]
Finally got all steps together :-) I also needed to update the list of compilation files after having generated the source files. With this last step in place, my C# project now builds sufficiently after code generation.

**Comment by ramondeklein** [comment]
> Finally got all steps together :-) I also needed to update the list of compilation files after having generated the source files. With this last step in place, my C# project now builds sufficiently after code generation.

Could you post the content of your .csproj file to show what you have done? I try to build in a .NET core v3.1 container with Gitlab CI/CD, so I ran into the same issue...

**Comment by anders9ustafsson** [comment]
This is what I included in the .csproj file:

    <ItemGroup>
      <TextTemplate Include="**\*.tt" />
      <Generated Include="**\*.Generated.cs" />
    </ItemGroup>

    <Target Name="TextTemplateTransform" BeforeTargets="BeforeBuild">
      <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet tool restore" />
      <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet tool run t4 %(TextTemplate.Identity) -I %(TextTemplate.RecursiveDir) -o %(TextTemplate.RecursiveDir)%(TextTemplate.Filename).Generated.cs" />
      <ItemGroup>
        <Compile Include="**/*$(DefaultLanguageSourceExtension)" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder);$(BaseIntermediateOutputPath)**;$(BaseOutputPath)**;@(Compile)" />
      </ItemGroup>
    </Target>

The `<Compile Include...` part is there to refresh the list of files to compile, to ensure that the files generated by the *dotnet-t4*  tool are included in the build.

In my *nuget.config* file I have added the following reference:

    <add key="github" value="https://nuget.pkg.github.com/mono/index.json" />

together with the package source credentials required by Github Packages, see [here](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-dotnet-cli-for-use-with-github-packages) for details.

**Comment by bdovaz** [comment]
Any news on this?

**Comment by APIWT** [comment]
> This is what I included in the .csproj file:
> 
> ```
> <ItemGroup>
>   <TextTemplate Include="**\*.tt" />
>   <Generated Include="**\*.Generated.cs" />
> </ItemGroup>
> 
> <Target Name="TextTemplateTransform" BeforeTargets="BeforeBuild">
>   <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet tool restore" />
>   <Exec WorkingDirectory="$(ProjectDir)" Command="dotnet tool run t4 %(TextTemplate.Identity) -I %(TextTemplate.RecursiveDir) -o %(TextTemplate.RecursiveDir)%(TextTemplate.Filename).Generated.cs" />
>   <ItemGroup>
>     <Compile Include="**/*$(DefaultLanguageSourceExtension)" Exclude="$(DefaultItemExcludes);$(DefaultExcludesInProjectFolder);$(BaseIntermediateOutputPath)**;$(BaseOutputPath)**;@(Compile)" />
>   </ItemGroup>
> </Target>
> ```
> 
> The `<Compile Include...` part is there to refresh the list of files to compile, to ensure that the files generated by the _dotnet-t4_ tool are included in the build.
> 
> The `Generated` item group is currently not used. Previously, I used it to identify which files to remove during _clean_, but it yielded unwanted compiler warnings. Hence I removed this usage altogether for the time being.
> 
> In my _nuget.config_ file I have added the following reference:
> 
> ```
> <add key="github" value="https://nuget.pkg.github.com/mono/index.json" />
> ```
> 
> together with the package source credentials required by Github Packages, see [here](https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-dotnet-cli-for-use-with-github-packages) for details.

This is working great for us. Thanks for the help! The only bummer (as you mentioned) is that Github requires credentials. No a huge issue but definitely inconvenient.

**Comment by mhutch** [comment]
I just pushed v2.2.0 to NuGet.org with .NET 5.0 support.
