### ISSUE TITLE
Specifying a parameter with an equal sign in it

### ISSUE THREAD

**Issue by APIWT** [mono/t4#71]
I am having trouble specifying a parameter with an equal sign in it.

Example: `t4 something.tt -o:something.cs /p:MyParam="testing="`

This appears to be an issue with this: https://github.com/mono/mono/blob/master/mcs/class/Mono.Options/Mono.Options/Options.cs#L570

Any suggestions on how to allow this as we have values with equal signs in them?

A full example: `echo "<#@ parameter name='Name' #>Hello <#=Name#>" | t4 -o - -p:Name='The World=Awesome'`

Expected output: `Hello The World = Awesome`
Actual output: `Hello The World`

Thanks!

**Comment by mhutch** [comment]
@jonpryor any ideas?

**Comment by APIWT** [comment]
@mhutch @jonpryor Any ideas on this? Thanks!

**Comment by APIWT** [comment]
Sorry to be annoying, but I was hoping for an update on this issue. @mhutch @jonpryor

**Comment by mhutch** [comment]
This is now fixed.
