### ISSUE TITLE
Type Environment exists in two assemblies

### ISSUE THREAD

**Issue by eltiare** [mono/t4#72]
I've installed the tool in a .Net Core 3.0 project. I'm using environment variables to build a credentials class. 

I get the following error: `/var/folders/qf/59827vqj0jz819fcpsr0dwtm0000gn/T/tmp6w9d0b.tmp/Credentials.tt(6,106): ERROR: The type 'Environment' exists in both 'System.Runtime.Extensions, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' and 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'`

From this code:

```
<#@ template debug="false" hostspecific="true" language="C#" #>
<#@ output extension=".cs" #>
namespace SosBackend {
	public static class Credentials {
		public static string DbUser = "<#= Environment.GetEnvironmentVariable("DB_USER") ?? "" #>";
		public static string DbPassword = "<#= Environment.GetEnvironmentVariable("DB_PASSWORD") ?? "" #>";
		public static string DbHost = "<#= Environment.GetEnvironmentVariable("DB_HOST") ?? "" #>";
		public static string DbDb = "<#= Environment.GetEnvironmentVariable("DB_DB") ?? "" #>";
		public static string DbPort = "<#= Environment.GetEnvironmentVariable("DB_PORT") ?? "1433" #>";
	}
}
```
I've tried ading both assemblies listed in assembly and import directives, with them not being found.

**Comment by NatElkins** [comment]
Hitting the same issue here, but with `System.Environment.NewLine`.

**Comment by mhutch** [comment]
Can you reproduce this in version 2.2?

**Comment by mhutch** [comment]
I tested this use case on 2.2.0 and it now works:

```bash
$ echo '<#=Environment.GetEnvironmentVariable("GREETING") ?? "" #>' | GREETING="hello" t4 -o -
hello
```

I also added an env var to disable the use of reference assemblies, to simulate behavior on machines where reference assemblies are not available, and it succeeds in that case too

```bash
$ echo '<#=Environment.GetEnvironmentVariable("GREETING") ?? "" #>' | T4_DEBUG_DISABLE_REF_ASMS=y GREETING="hello" dotn
et run --no-build -- -o -
hello
```
