### ISSUE TITLE
Mono.TextTemplating.Roslyn package not published to nuget.org

### ISSUE THREAD

**Issue by luiscnsousa** [mono/t4#76]
Mono.TextTemplating.Roslyn is a nice addition to Mono.TextTemplating to use the In-process Roslyn compiler, but unfortunately it cannot be found on nuget.org yet because there there hasn't been a new release in a while. The latest one dates June 13th 2019.

Is it possible to have it included in the next release and published?

**Comment by mhutch** [comment]
Yes, i'll include it in the next release.

For now, you can get it from GitHub Package Registry: https://github.com/mono/t4/packages

**Comment by mhutch** [comment]
It's on NuGet.org now: https://www.nuget.org/packages/Mono.TextTemplating.Roslyn/

Apologies for the delay!
