### ISSUE TITLE
using a parameter directive result in missing reference

### ISSUE THREAD

**Issue by kccarter76** [mono/t4#87]
The type 'CompilerErrorCollection' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.CodeDom, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

 The type or namespace name 'Messaging' does not exist in the namespace 'System.Runtime.Remoting' (are you missing an assembly reference?)

**Comment by mhutch** [comment]
Do you have a repro for this? From the linked commits it looks like this is related to generating/compiling on one runtime and running on another.

**Comment by kccarter76** [comment]
This is in my fork of the mono library

**Comment by mhutch** [comment]
Ok, if it doesn't apply to this version of the library I'll close the issue.
